###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "test3",
    "lastname": "test3",
    "email": "test@test3.com",
    "current_pasword": "User123"
} 

###
GET http://localhost:3100/api/v1/users/ HTTP/1.1
###
GET http://localhost:3100/api/v1/users/653194def2c96b89a367e22d HTTP/1.1
###
DELETE  http://localhost:3100/api/v1/users/6540acb746dfd19c912a3228 HTTP/1.1
###
PATCH  http://localhost:3100/api/v1/users/6511ef215d8421dd3328f042 HTTP/1.1
Content-Type: application/json

{
    "firstname": "test1",
    "lastname": "test uno lastname"
}

###
PUT   http://localhost:3100/api/v1/users/6540658ed0c4896e27ae38ff HTTP/1.1
Content-Type: application/json

{
    "active":true
}

//sesion

###
POST http://localhost:3100/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "fistname": "pepito",
    "lastname": "alcachofa",
    "email": "alcachofa@test.com",
    "current_password": "alcachofa123",
    "phone": "3117752691"
}


###
POST http://localhost:3100/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "alcachofa@test.com",
    "current_password": "alcachofa123"
}

###
GET http://localhost:3100/api/v1/auth/get-me/6540658ed0c4896e27ae38ff HTTP/1.1